services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: mysql
      MYSQL_DATABASE: homepage
    volumes:
      - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
  prod:
    build:
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - './.env'
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
volumes:
  mysql: ~
  dev:
